vich_uploader:
    db_driver: orm

    mappings:
        offreStage:
            uri_prefix: /upload/offre-stage
            upload_destination: '%kernel.project_dir%/public/upload/offre-stage'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
        cv:
            uri_prefix: /upload/cv
            upload_destination: '%kernel.project_dir%/public/upload/cv'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
